export type HardwarePrice = { value: number; currency: string; region?: string; source: string; date: string; seller?: string };
export type Device = { id: string; name: string; class: string; memory_gb: number | null; memory_kind?: string; gpu?: string; supports_image?: boolean; prices?: HardwarePrice[]; notes?: string };
export type DeviceClass = { id: string; title: string; platforms: string[]; memory_kind?: string; device_ids: string[]; auto_suggest: boolean; base_system_by_currency?: Record<string, number>; composition?: string; accelerator?: string; availability_note?: string; runs_today_basis?: string };
export type Variant = { id?: string; precision?: string; min_vram_gb?: number; recommended_vram_gb?: number; min_ram_gb?: number; platforms?: string[] };
export type HardwareModel = { variants?: Variant[]; modalities?: string[]; params?: { total_b?: number }; installer_policy?: { status?: string } };
export function median(values: number[]): number | null;
export function marginQuote(streetPrice: number): number | null;
export function deviceStreetPrices(device: Device, definition?: DeviceClass): Record<string, number | null>;
export function deviceQuotes(device: Device, definition?: DeviceClass): Record<string, number | null>;
export function deviceFits(model: HardwareModel, device: Device, variant?: Variant, classes?: DeviceClass[]): boolean;
export function suggestDevice(model: HardwareModel, devices: Device[], classes?: DeviceClass[]): null | { id: string; name: string; class: string; memory_gb: number; memory_kind?: string; variant_id: string | null; platforms: string[]; price_usd: number | null; price_eur: number | null; street_prices: Record<string, number | null>; source: Array<{ source: string; date: string; currency: string; value: number }> };
