import type { Metadata } from "next";
import Link from "next/link";
import { BILLING_PORTAL_LOGIN_URL } from "@/lib/billing";
import { LicenceCheckoutForm } from "@/components/licence-checkout-form";

export const metadata: Metadata = { title: "Installer licence", alternates: { canonical: "/local/licence" } };

export default function LicencePage() {
  return <>
    <section className="section-wrap hero"><p className="eyebrow">Local installer licence</p><h1>Simple terms for small teams.</h1><p className="lede">The free plan is for individuals and smaller companies. Larger companies can use the commercial installer licence.</p></section>
    <section className="section-wrap section split" id="pricing">
      <article className="price-card licence-card"><p className="section-kicker">Free</p><h2>Personal and smaller companies</h2><p className="price licence-price">$0 <span>to use the installer</span></p><ul><li>Individuals</li><li>Companies with up to 10 employees and annual recurring revenue (ARR) of up to USD 1 million</li><li>Use the local installer under its free terms</li></ul><p className="trust-note"><strong>We don&apos;t check — we trust you.</strong></p><Link href="#terms" className="button button-secondary">Read the installer terms</Link></article>
      <article className="price-card featured licence-card"><p className="section-kicker">Commercial</p><h2>For companies above either threshold</h2><p className="price licence-price">$1,000 <span>one-time setup</span></p><p className="price licence-price">$100/month</p><ul><li>Required when a company has more than 10 employees or more than USD 1 million in annual recurring revenue (ARR)</li><li>One-time setup fee and monthly subscription</li><li>Cancel any time through the customer portal</li></ul><p>Applicable taxes are calculated at checkout.</p></article>
      <p className="source-note full-width">Source: <a href="#terms">Decision Models local installer licence terms</a> · checked 9 October 2026.</p>
    </section>
    <section className="section-wrap section detail-grid" id="checkout">
      <div><p className="section-kicker">Commercial checkout</p><h2>Start the commercial licence</h2><p className="lede">We use your declaration to place the order. No company-size verification is performed during checkout.</p><div className="panel space-top"><LicenceCheckoutForm /></div></div>
      <aside className="stack"><div className="callout"><strong>Model licences are separate.</strong><p>The installer licence does not change the rights attached to model weights. Check the model&apos;s own licence before commercial use or redistribution.</p></div><div className="panel"><h3>What you get</h3><p>After checkout, we email a one-time licence key and provide an activation command. Keep the key in your company&apos;s approved secret storage.</p><div className="command-line"><code>dm-local licence activate &lt;key&gt;</code></div></div></aside>
    </section>
    <section className="section-wrap section" id="terms"><div className="panel"><h2>Installer terms</h2><p>Individuals and companies with up to 10 employees and up to USD 1 million annual recurring revenue can use the installer free. A company above either threshold needs the commercial licence: USD 1,000 once plus USD 100 per month, with applicable taxes shown at checkout. We use your self-declaration without company-size verification.</p><p>The commercial licence covers use of the Decision Models installer while the subscription is active. Model licences apply separately; this purchase does not change their commercial-use or redistribution terms. Cancellation stops renewal at the end of the paid billing period.</p><p><a href={BILLING_PORTAL_LOGIN_URL}>Manage billing or cancel renewal →</a> · Sign in with your checkout email. For help, email <a href="mailto:info@decisionmodels.io">info@decisionmodels.io</a>.</p></div></section>
    <section className="section-wrap section"><div className="section-heading"><div><p className="section-kicker">Questions</p><h2>Licence details</h2></div></div><div className="faq">
      {[ ["How do you count employees?", "Use the number of employees at the time the licence is used."], ["What counts as annual recurring revenue?", "Use your company's annual recurring revenue (ARR). Companies with up to 10 employees and ARR up to USD 1 million meet the free plan thresholds."], ["Can I cancel the monthly subscription?", "Yes. Open the Stripe customer portal from the success page or use the billing portal link in your licence email. Cancellation stops future renewals under Stripe's billing schedule."], ["Are prices tax inclusive?", "Applicable taxes are calculated at checkout."], ["Does this licence clear model usage?", "No. The model's own licence controls its weights, outputs, and redistribution. Check the model's own licence on its model page."], ["Do you verify the company declaration?", "No. We don't check — we trust you. The commercial checkout records your company name and declaration for the licence record."] ].map(([question, answer]) => <details className="disclosure" key={question}><summary>{question}</summary><p>{answer}</p></details>)}
    </div></section>
  </>;
}
